name: test-meta

on:
  push:
    branches:
      - 'master'
    tags:
      - 'php-apache/v*'
  pull_request:
    branches:
      - 'master'

  # schedule:
  #   - cron: "0 0 * * 1" # each monday at 0:00

jobs:
  build-test:
    runs-on:  ubuntu-latest
    strategy:
      matrix:
        base: ["3.14"]
        simplesaml: ["1.1.19", "2.0.11"]
        composer: ["1", "2"]
    outputs:
      tags: ${{ steps.meta.outputs.tags }}   
      labels: ${{ steps.meta.outputs.labels }}   
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=auto
            suffix=-ssaml-${{ matrix.simplesaml }}-cpsr-${{ matrix.composer }}-alp-${{ matrix.base }},onlatest=true
          images: |
            europe-docker.pkg.dev/hr-shared-gar-prod-0i8s/hr-docker/php
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=php-apache/v(.*),group=1
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            ALPINE-VERSION=${{ matrix.base }}
            SIMPLESAML_VERSION=${{ matrix.simplesaml }}
            COMPOSER_VERSION=${{ matrix.composer }}
