name: Deploy Prod

on: push


jobs:
  Build:
    name: Build Dev
    runs-on:  ubuntu-latest
    steps:

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set SOURCE env
      run: |-
        echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Set TAG master
      run: |-
        echo "master"
        echo "TAG_NAME='latest'" >> $GITHUB_ENV
      if: env.SOURCE_BRANCH == 'master'
    - name: Set TAG version
      run: |-
        echo "TAG_NAME=${{env.SOURCE_TAG}}" >> $GITHUB_ENV
      if: env.SOURCE_BRANCH != 'master' && contains(env.SOURCE_BRANCH , 'refs/tags')
    - name: Set TAG branch
      run: |-
        echo "TAG_NAME=${{env.SOURCE_BRANCH}}" >> $GITHUB_ENV
      if: env.SOURCE_BRANCH != 'master' && !contains(env.SOURCE_BRANCH , 'refs/tags')


    - name: Build
      run: |-
        echo ${{env.SOURCE_BRANCH}}
        echo ${{env.SOURCE_TAG}}
        echo ${{env.TAG_NAME}}

