name: Deploy Prod

on: push


jobs:
  Build:
    name: Build Dev
    runs-on:  ubuntu-latest
    steps:

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set SOURCE env
      run: |-
        echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Set TAG master
      run: |-
        echo "TAG_NAME=latest" >> $GITHUB_ENV
      if: env.SOURCE_BRANCH == "master"
    - name: Set TAG "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}"
      run: |-
        echo "TAG_NAME=${{env.SOURCE_TAG}}" >> $GITHUB_ENV
      if: env.SOURCE_BRANCH != "master" && env.SOURCE_TAG == ""
    - name: Set TAG "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}"
      run: |-
        echo "TAG_NAME=${{env.SOURCE_BRANCH}}" >> $GITHUB_ENV
      if: env.SOURCE_BRANCH != "master" && env.SOURCE_TAG != ""


    - name: Build
      run: |-
        echo ${{env.SOURCE_BRANCH}}
        echo ${{env.SOURCE_TAG}}
        echo ${{env.TAG_NAME}}

